name=isbFilters
version=0.0.1
author=Adaptado de Pieter P
maintainer=Moises Meza
sentence=This is a library for digital finite impulse response and infinite impulse response filters for Arduino.
paragraph=
category=Data Processing
url=https://github.com/tttapa/Filters
architectures=*
includes=FIRFilter.h,IIRFilter.h
